### PR TITLE
woof

### PR DESCRIPTION
**Pull request by LukeMondy**

### CODE REVIEW

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 24961bfbb5762c19c71a9b104b6a68803222acbd

### Summary

| Test name | Result |
| --- | --- |
| Testing project -  lmondy - More github workflow - EXT-LukeMondy-a_new_pr-9 | FAILED |
| Testing project -  lmondy - Test GitHub workflow - EXT-LukeMondy-a_new_pr-9 | SUCCESSFUL |
### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Testing project -  lmondy - More github workflow - EXT-LukeMondy-a_new_pr-9 | Stage 2 | 1 of 2 jobs failed |

**Job: Second phase**
Build logs
```
25-Sep-2019 15:47:28	Build Testing project -  lmondy - More github workflow - EXT-LukeMondy-a_new_pr-9 - Second phase #1 (LMONDY-MGW8-SP-1) started building on agent A local agent 1
25-Sep-2019 15:47:28	I run on the Bamboo server!
25-Sep-2019 15:47:28	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/LMONDY-MGW8-SP
25-Sep-2019 15:47:28	Executing build Testing project -  lmondy - More github workflow - EXT-LukeMondy-a_new_pr-9 - Second phase #1 (LMONDY-MGW8-SP-1)
25-Sep-2019 15:47:28	Starting task 'Checkout Default Repository' of type 'com.atlassian.bamboo.plugins.vcs:task.vcs.checkout'
25-Sep-2019 15:47:28	Checking out into /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/LMONDY-MGW8-SP
25-Sep-2019 15:47:28	Updating source code to revision: 24961bfbb5762c19c71a9b104b6a68803222acbd
25-Sep-2019 15:47:28	Fetching 'refs/heads/EXT-LukeMondy-a_new_pr-9' from 'ssh://git@bitbucket.ts.data61.csiro.au:7999/~lukemondy/test-repo.git'.
25-Sep-2019 15:47:28	Warning: Permanently added '[127.0.0.1]:41513' (RSA) to the list of known hosts.
25-Sep-2019 15:47:29	Checking out revision 24961bfbb5762c19c71a9b104b6a68803222acbd.
25-Sep-2019 15:47:29	Creating local git repository in '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/LMONDY-MGW8-SP/.git'.
25-Sep-2019 15:47:29	Cloning into '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/LMONDY-MGW8-SP'...
25-Sep-2019 15:47:29	done.
25-Sep-2019 15:47:29	Switched to a new branch 'EXT-LukeMondy-a_new_pr-9'
25-Sep-2019 15:47:29	Branch 'EXT-LukeMondy-a_new_pr-9' set up to track remote branch 'EXT-LukeMondy-a_new_pr-9' from 'origin'.
25-Sep-2019 15:47:29	Updated source code to revision: 24961bfbb5762c19c71a9b104b6a68803222acbd
25-Sep-2019 15:47:29	Finished task 'Checkout Default Repository' with result: Success
25-Sep-2019 15:47:29	Running pre-build action: VCS Version Collector
25-Sep-2019 15:47:29	Starting task 'Script' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
25-Sep-2019 15:47:29	+ random=4
25-Sep-2019 15:47:29	+ echo 4
25-Sep-2019 15:47:29	4
25-Sep-2019 15:47:29	+ [[ 4 = \4 ]]
25-Sep-2019 15:47:29	+ echo 'Some output'
25-Sep-2019 15:47:29	Some output
25-Sep-2019 15:47:29	+ sleep 16
25-Sep-2019 15:47:45	+ echo 'This was a bad build'
25-Sep-2019 15:47:45	+ echo 'This was a bad build'
25-Sep-2019 15:47:45	+ echo 'This was a bad build'
25-Sep-2019 15:47:45	+ echo 'This was a bad build'
25-Sep-2019 15:47:45	+ echo 'This was a bad build'
25-Sep-2019 15:47:45	+ exit 1
25-Sep-2019 15:47:45	This was a bad build
25-Sep-2019 15:47:45	This was a bad build
25-Sep-2019 15:47:45	This was a bad build
25-Sep-2019 15:47:45	This was a bad build
25-Sep-2019 15:47:45	This was a bad build
25-Sep-2019 15:47:45	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/LMONDY-MGW8-SP-1-ScriptBuildTask-7558109224896482420.sh] was 1 while expected 0
25-Sep-2019 15:47:45	Finished task 'Script' with result: Failed
25-Sep-2019 15:47:45	Running post build plugin 'NCover Results Collector'
25-Sep-2019 15:47:45	Running post build plugin 'Artifact Copier'
25-Sep-2019 15:47:45	Running post build plugin 'npm Cache Cleanup'
25-Sep-2019 15:47:45	Running post build plugin 'Clover Results Collector'
25-Sep-2019 15:47:45	Running post build plugin 'Docker Container Cleanup'
25-Sep-2019 15:47:45	Finalising the build...
25-Sep-2019 15:47:45	Stopping timer.
25-Sep-2019 15:47:45	Build LMONDY-MGW8-SP-1 completed.
25-Sep-2019 15:47:45	Running on server: post build plugin 'NCover Results Collector'
25-Sep-2019 15:47:45	Running on server: post build plugin 'Build Hanging Detection Configuration'
25-Sep-2019 15:47:45	Running on server: post build plugin 'Clover Delta Calculator'
25-Sep-2019 15:47:45	Running on server: post build plugin 'Maven Dependencies Postprocessor'
25-Sep-2019 15:47:45	All post build plugins have finished
25-Sep-2019 15:47:45	Generating build results summary...
25-Sep-2019 15:47:45	Saving build results to disk...
25-Sep-2019 15:47:45	Logging substituted variables...
25-Sep-2019 15:47:45	Indexing build results...
25-Sep-2019 15:47:45	Finished building LMONDY-MGW8-SP-1.
```

**Comment by LukeMondy** [comment]
hello
Koala

**Comment by LukeMondy** [comment]
back_logo

**Pull request closed without merging**
