### PR TITLE
Speak in French.

### PR DESCRIPTION
**Pull request by wom-bat**
@ssrg-bamboo `test`

### CODE REVIEW

**Comment by LukeMondy** [comment]
@ssrg-bamboo

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by wom-bat** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 2a472c884a5f7ae5c53a0bc66eafa06d422c43b3

### Summary

| Test name | Result |
| --- | --- |
| Testing project -  lmondy - More github workflow - EXT-wom-bat-master-6 | SUCCESSFUL |
| Testing project -  lmondy - Test GitHub workflow - EXT-wom-bat-master-6 | SUCCESSFUL |

**Pull request merged**
