### PR TITLE
Added hello2

### PR DESCRIPTION
**Pull request by WellMcGarnicle**

### CODE REVIEW

**Comment by WellMcGarnicle** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by LukeMondy** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR internally and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit c2d013a0ea1c576437e7ceb1d6aae1d1a6d4d651

### Summary

| Test name | Result |
| --- | --- |
| Testing project -  lmondy - More github workflow - EXT-WellMcGarnicle-master-5 | FAILED |
| Testing project -  lmondy - Test GitHub workflow - EXT-WellMcGarnicle-master-5 | SUCCESSFUL |
### Detailed failure logs

**Testing project -  lmondy - More github workflow - EXT-WellMcGarnicle-master-5**

Oh no!

**Pull request closed without merging**
